import React from 'react';
import {DateInput} from './DateInput';
import {BottomNav} from './BottomNav';
import type {AppView} from './BottomNav';
import { missions, sleepResult, progress } from './domain/game';
import {previewMission} from './domain/preview';
import type { Result } from './domain/game';
import { db, localDay, addEntry, setDecision, queueClose, weekStart, previousDay } from './storage';
import type { Entry, Decision, Snapshot, Objectives, Evaluation, Movement } from './storage';
import './style.css';
import { liveQuery } from 'dexie';
const Shop=React.lazy(()=>import('./Shop').then(module=>({default:module.Shop})));
const Tools=React.lazy(()=>import('./Tools').then(module=>({default:module.Tools})));
const History=React.lazy(()=>import('./Reports').then(module=>({default:module.History})));
const Progress=React.lazy(()=>import('./Reports').then(module=>({default:module.Progress})));
const Rules=React.lazy(()=>import('./Rules').then(module=>({default:module.Rules})));
import {EntryCorrection} from './EntryCorrection';
const initialObjectives:Objectives={status:'unverified',rank:'D',pushups:10,abs:10,squats:10,steps:1000,reading:10};
const order=['pushups','abs','squats','steps','reading','coach','airofit','word','control','food','alcohol','focus','sleep'];
const labels:Record<Result,string>={pending:'Pendiente',fulfilled:'Cumplida · provisional',failed:'Incumplida · provisional',ticket:'Ticket',exempt:'Exenta · provisional'};
export function App(){
 const [view,setView]=React.useState<AppView>('today');
 React.useEffect(()=>{window.scrollTo(0,0);},[view]);
 const [day,setDay]=React.useState(localDay());
 const editorRef=React.useRef<HTMLElement>(null);
 const [entries,setEntries]=React.useState<Entry[]>([]),[decisions,setDecisions]=React.useState<Decision[]>([]);
 const [account,setAccount]=React.useState<Snapshot|null>(null),[objectives,setObjectives]=React.useState(initialObjectives),[evaluations,setEvaluations]=React.useState<Evaluation[]>([]),[movements,setMovements]=React.useState<Movement[]>([]);
 const goals:Record<string,number>={pushups:objectives.pushups,abs:objectives.abs,squats:objectives.squats,steps:objectives.steps,reading:objectives.reading};
 const player=progress(account?.balances?.xp||0);
 const [active,setActive]=React.useState<string|null>(null),[error,setError]=React.useState(''),[notice,setNotice]=React.useState(''),[pending,setPending]=React.useState(0),[busy,setBusy]=React.useState(false),[review,setReview]=React.useState(false),[loaded,setLoaded]=React.useState(false);
 React.useEffect(()=>{if(active)editorRef.current?.scrollIntoView({block:'start'});},[active]);
 const load=React.useCallback(async()=>{const [a,b,c,state,record,closed,ledger]=await Promise.all([db.entries.where('day').equals(day).toArray(),db.decisions.where('day').equals(day).toArray(),db.operations.where('status').anyOf('pending','conflict').count(),db.meta.get('account'),db.days.get(day),db.evaluations.where('day').equals(day).toArray(),db.movements.toArray()]);return {a,b,c,state,record,closed,ledger};},[day]);
 React.useEffect(()=>{setLoaded(false);const sub=liveQuery(load).subscribe({next:({a,b,c,state,record,closed,ledger})=>{setEntries(a);setDecisions(b);setPending(c);setAccount(state?.value||null);setObjectives(record?.objectives||initialObjectives);setEvaluations(closed);setMovements(ledger);setLoaded(true);},error:()=>setError('No se pudo abrir el almacenamiento local. No registres datos hasta resolverlo.')});return()=>sub.unsubscribe();},[load]);
 async function save(action:()=>Promise<void>){setBusy(true);setError('');try{await action();setActive(null);setNotice('Guardado en este dispositivo. Usa el icono de sincronización del header para confirmar la copia remota.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar. El formulario permanece abierto; vuelve a intentarlo.');}finally{setBusy(false);}}
 const outcomes=missions.map(m=>previewMission(m,entries,decisions,objectives));
 const gains=outcomes.reduce((a,o)=>{const old=evaluations.find(e=>e.mission===o.m.id);return {xp:a.xp+o.effect.xp-(old?.xp||0),mc:a.mc+o.effect.mc-(old?.mc||0)};},{xp:0,mc:0});
 const allResolved=outcomes.every(o=>o.result!=='pending');
 const allAccounted=allResolved&&outcomes.every(o=>evaluations.some(e=>e.mission===o.m.id&&e.result===o.result&&e.xp===o.effect.xp&&e.mc===o.effect.mc));
 const [changeReview,setChangeReview]=React.useState<{action:()=>Promise<void>;mission:string;before:string;after:string;old:{xp:number;mc:number};next:{xp:number;mc:number};signature:string}|null>(null);
 const signature=(a:Entry[],b:Decision[])=>JSON.stringify([a.slice().sort((x,y)=>x.id.localeCompare(y.id)),b.slice().sort((x,y)=>x.id.localeCompare(y.id))]);
 function reviewChange(action:()=>Promise<void>,mission:string,nextEntries:Entry[],nextDecisions:Decision[],description:string){
 const m=missions.find(m=>m.id===mission)!,old=evaluations.find(e=>e.mission===mission)||previewMission(m,entries,decisions,objectives).effect,next=previewMission(m,nextEntries,nextDecisions,objectives).effect;
 const original=decisions.find(d=>d.mission===mission);
 setNotice('Revisa la comparación debajo del formulario antes de confirmar.');
 setChangeReview({action,mission,before:original?`${original.result} · ${original.detail}`:'Sin decisión previa',after:description,old,next,signature:signature(entries,decisions)});
 }
 function requestDecision(value:Omit<Decision,'id'|'revision'>){const next={...value,id:`${day}:${value.mission}`};reviewChange(()=>setDecision(value),value.mission,entries,[...decisions.filter(d=>d.mission!==value.mission),next],`${value.result} · ${value.detail}`);}
 function requestEntry(value:Omit<Entry,'id'|'revision'>){if(!evaluations.some(e=>e.mission===value.mission)){void save(()=>addEntry(value));return;}reviewChange(()=>addEntry(value),value.mission,[...entries,{...value,id:'preview'}],decisions,`Añadir ${value.quantity} ${value.unit} · ${value.occurredAt} · ${value.note}`);}
 const selected=missions.find(m=>m.id===active);
 const tabs=<BottomNav view={view} onNavigate={setView}/>;
 if(view==='rules')return <main className="app-main">{tabs}<Rules/></main>;
 if(view==='tools')return <main className="app-main">{tabs}<Tools canUpdate={!active&&!busy}/></main>;
 if(view==='history'||view==='progress')return <main className="app-main">{tabs}{view==='history'?<History onEdit={value=>{setDay(value);setActive(null);setReview(false);setView('today');}}/>:<Progress provisional={gains} day={day}/>}</main>;
 if(view==='shop')return <main className="app-main">{tabs}<Shop/></main>;
 return <main className="app-main">{tabs}<p className="muted">Cola de sincronización · {pending} operaciones pendientes</p><label>Fecha del registro<DateInput type="date" min="2026-10-05" max="2026-12-31" disabled={busy} value={day} onChange={e=>{if(e.target.value){setDay(e.target.value);setChangeReview(null);setActive(null);setReview(false);}}}/></label><h1>{day===localDay()?"Hoy":day}</h1>{account?.importedUnverified&&<p role="status">Copia restaurada pendiente de verificar. Sincroniza para confirmar XP y MC con el servidor.</p>}<p className="muted">Objetivos del día: rango {objectives.rank} · {objectives.status==='verified'?'verificados':'pendientes de verificar'}</p>{error&&<p role="alert" className="error">{error}</p>}<p aria-live="polite">{notice}</p><h2>Misiones del día</h2><p className="muted">{allAccounted?`Día completo · ${outcomes.length} misiones contabilizadas`:allResolved?`${outcomes.length} misiones resueltas · listo para cerrar el día`:'Día en progreso · faltan misiones por resolver'}</p>{outcomes.sort((a,b)=>order.indexOf(a.m.id)-order.indexOf(b.m.id)).map(({m,total,result,effect})=><section className="mission" key={m.id}><div className="row"><div><h3>{m.name}</h3><p className="muted">{goals[m.id]?`${total} / ${goals[m.id]} ${m.id==='steps'?'pasos':m.id==='reading'?'páginas':'repeticiones'}`:m.episodic?`${total} episodios/unidades registrados`:m.id==='sleep'?'22:30 → 06:30 · mínimo 7 h':m.id==='airofit'?'Seguir el entrenamiento diario planificado por Airofit':'Plan prescrito'}</p></div><button disabled={!loaded||busy||day<'2026-10-05'||day>'2026-12-31'} onClick={()=>setActive(m.id)}>Registrar</button></div><p className="muted">{m.xp} XP / {m.mc} MC · Penalización: −{m.mc*5} MC{m.episodic?' por episodio':' por '+(m.id==='sleep'?'noche':'día')}</p><p className={result==='failed'?'error':'success'}>{evaluations.some(e=>e.mission===m.id&&e.result===result&&e.xp===effect.xp&&e.mc===effect.mc&&result!=='pending')?'Contabilizada · '+labels[result].split(' ·')[0]:labels[result]}</p></section>)}
 {selected&&<section ref={editorRef} className="hero editor" aria-label={`Registro de ${selected.name}`}><h2>{selected.name}</h2><form key={selected.id} onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget);const note=String(form.get('note')||'');const mode=String(form.get('mode')||'entry');
 if(selected.id==='airofit'&&!account?.airofitEnabled){setError('Aplica la migración 007 y sincroniza para registrar Airofit.');return;}
 if(selected.id==='sleep'&&account?.sleepReference!=='wake-day'){setError('Sincroniza después de aplicar la migración 005 para registrar la noche anterior.');return;}
 if((mode==='exempt'||evaluations.some(e=>e.mission===selected.id))&&!note.trim()){setError('Documenta el motivo de la exención o de la corrección de una misión contabilizada.');return;}
 if(mode==='entry'){
 const quantity=Number(form.get('quantity'));if(!Number.isSafeInteger(quantity)||quantity<=0){setError('Introduce una cantidad entera positiva.');return;}
 const occurredAt=String(form.get('occurredAt')||`${day}T12:00`);if(!occurredAt.startsWith(day)){setError('El episodio debe corresponder al día seleccionado.');return;}
 const ticket=(account?.tickets||[]).find(t=>t.id===form.get('ticketId')&&t.product==='food'&&t.assignedAt.startsWith(day));
 requestEntry({day,mission:selected.id,quantity,correctionReason:note,unit:String(form.get('unit')||'unidad'),note,occurredAt,...(ticket?{ticketId:ticket.id,mealAt:ticket.assignedAt,mealLabel:ticket.label}:{})});
 }else if(selected.id==='sleep'&&(mode==='fulfilled'||mode==='failed')){
 const bedAt=String(form.get('bedAt')||''),wakeAt=String(form.get('wakeAt')||''),minutes=Number(form.get('minutes')),coverage=String(form.get('coverage')||'strict') as 'strict'|'flexible'|'ticket';
 const bedTime=new Date(bedAt+'-05:00').getTime(),wakeTime=new Date(wakeAt+'-05:00').getTime();
 if(bedAt.slice(0,10)<previousDay(day)||bedAt.slice(0,10)>day||!Number.isFinite(bedTime)||!Number.isFinite(wakeTime)||wakeTime<=bedTime||wakeTime>Date.now()||wakeAt.slice(0,10)!==day||!String(form.get('minutes')||'')||!Number.isSafeInteger(minutes)||minutes<0||minutes>(wakeTime-bedTime)/60000){setError('Comprueba las fechas, horas y minutos efectivos de sueño. Registra la noche después de levantarte.');return;}
 const ticket=(account?.tickets||[]).find(t=>t.id===form.get('ticketId')&&t.product==='sleep'&&t.wakeDay===day);
 if(coverage==='ticket'&&!ticket){setError('Selecciona el ticket asignado a esta noche.');return;}
 const flex=account?.flexibility?.find(f=>f.weekStart===weekStart(day));
 if(coverage==='flexible'&&flex&&flex.night!==day){setError('La noche flexible de esta semana está asignada a otra noche.');return;}
 const result=sleepResult(bedAt.slice(11),wakeAt.slice(11),minutes,coverage);
 requestDecision({day,mission:selected.id,result,detail:JSON.stringify({bed:bedAt.slice(11),wake:wakeAt.slice(11),bedAt,wakeAt,minutes,coverage,sleepReference:'wake-day',ticketId:coverage==='ticket'?ticket?.id:undefined,night:day,note})});
 }else requestDecision({day,mission:selected.id,result:mode as Result,detail:JSON.stringify({note,coach:form.get('coach'),...(selected.id==='airofit'?{planCompleted:mode==='fulfilled'}:{})})});
 }}>
 <label>Tipo de registro<select name="mode"><option value={goals[selected.id]||selected.episodic?'entry':'fulfilled'}>{goals[selected.id]?'Añadir cantidad':selected.episodic?'Registrar episodio':'Registrar cumplimiento'}</option>{selected.episodic&&<option value="fulfilled">Confirmar cumplimiento</option>}{!selected.episodic&&selected.id!=='sleep'&&<option value="failed">Confirmar incumplimiento</option>}<option value="pending">Dejar pendiente</option><option value="exempt">Documentar exención</option></select></label>
 {(goals[selected.id]||selected.episodic)&&<><label>Cantidad<input name="quantity" type="number" min="1" step="1" defaultValue="1"/></label><label>Unidad o porción<input name="unit" defaultValue={selected.id==='alcohol'?'trago':selected.id==='reading'?'página':selected.id==='steps'?'paso':'unidad'}/></label><label>Fecha y hora del registro (Bogotá)<DateInput name="occurredAt" type="datetime-local" defaultValue={`${day}T12:00`}/></label></>}
 {selected.id==='airofit'&&<><p className="muted">Confirma el cumplimiento cuando completes el entrenamiento planificado por la app de Airofit para este día. Se realiza a diario, sin días de descanso; no exige un número fijo de minutos ni sesiones.</p>{!account?.airofitEnabled&&<p role="status">Aplica la migración 007 y sincroniza para habilitar esta misión.</p>}</>}
 {selected.id==='coach'&&<label>Plan prescrito<select name="coach"><option>Entrenamiento prescrito</option><option>Descanso prescrito</option></select></label>}
 {selected.id==='food'&&<label>Cobertura<select name="ticketId"><option value="">Sin ticket · porción sujeta a sanción</option>{account?.tickets?.filter(t=>t.product==='food'&&t.assignedAt.startsWith(day)).map(t=><option key={t.id} value={t.id}>{t.label} · {t.assignedAt.replace('T',' ')}</option>)}</select></label>}
 {selected.id==='sleep'&&<><p className="muted">Descanso del {day}: noche del {previousDay(day)} al {day}.</p>{account?.sleepReference!=='wake-day'&&<p role="status">Aplica la migración 005 y sincroniza para habilitar la noche anterior.</p>}<label>Fecha y hora de acostarte (Bogotá)<DateInput type="datetime-local" name="bedAt" defaultValue={`${previousDay(day)}T22:30`}/></label><label>Fecha y hora de levantarte (Bogotá)<DateInput type="datetime-local" name="wakeAt" defaultValue={`${day}T06:30`}/></label><label>Minutos efectivamente dormidos<input name="minutes" type="number" min="0" step="1"/></label><label>Cobertura<select name="coverage"><option value="strict">Horario exacto · 22:30 → 06:30</option><option value="flexible" disabled={account?.sleepReference!=='wake-day'}>Noche flexible · 1 por semana</option><option value="ticket" disabled={!account?.tickets?.some(t=>t.product==='sleep'&&t.wakeDay===day)}>Ticket de noche libre</option></select></label><label>Ticket asignado a esta noche<select name="ticketId"><option value="">Sin ticket seleccionado</option>{account?.tickets?.filter(t=>t.product==='sleep'&&t.wakeDay===day).map(t=><option value={t.id} key={t.id}>{t.label}</option>)}</select></label><p className="muted">La noche se contabiliza en el día en que te levantas. Las tres opciones exigen 7 h efectivas. La noche flexible conserva 15 XP / 3 MC; un ticket válido cubre el horario sin premios. El servidor confirma el cupo semanal.</p></>}

 <label>{selected.episodic?'Detalle del episodio y nota opcional':'Nota / motivo de exención'}<textarea name="note" maxLength={2000}/></label><div className="actions"><button disabled={busy} type="submit">{busy?'Guardando…':'Guardar registro'}</button><button type="button" disabled={busy} onClick={()=>setActive(null)}>Cancelar</button></div></form></section>}
 {changeReview&&<section className="hero editor" aria-label="Comparación antes de guardar"><h2>Revisar cambio de {missions.find(m=>m.id===changeReview.mission)?.name}</h2><p>Anterior: {changeReview.before}</p><p>Propuesto: {changeReview.after}</p><p>Resultado económico: {changeReview.old.xp} XP / {changeReview.old.mc} MC → {changeReview.next.xp} XP / {changeReview.next.mc} MC.</p><p>Diferencia provisional: {changeReview.next.xp-changeReview.old.xp} XP / {changeReview.next.mc-changeReview.old.mc} MC. Nivel previsto: {progress(Math.max(0,(account?.balances?.xp||0)+changeReview.next.xp-changeReview.old.xp)).level}.</p><p>Si cambia una misión contabilizada, el servidor revierte su efecto anterior y aplica el nuevo. Los objetivos históricos se conservan. Las misiones abiertas se contabilizan al cerrar.</p><button disabled={busy} onClick={()=>void save(async()=>{const store=db;await store.transaction('rw',store.entries,store.decisions,store.operations,async()=>{const a=await store.entries.where('day').equals(day).toArray(),b=await store.decisions.where('day').equals(day).toArray();if(signature(a,b)!==changeReview.signature)throw new Error('Cambió el día; prepara otra comparación.');await changeReview.action();});setChangeReview(null);})}>Confirmar cambio</button><button disabled={busy} onClick={()=>setChangeReview(null)}>Cancelar cambio</button></section>}
 <section className="hero"><div className="row"><h2>Balance provisional</h2><span aria-live="polite">{gains.xp} XP · {gains.mc>=0?'+':''}{gains.mc} MC</span></div><p className="muted">{outcomes.filter(o=>o.result==='pending').length} misiones pendientes. Los importes provisionales muestran la diferencia frente a lo ya contabilizado.</p><button disabled={!loaded||busy} onClick={()=>setReview(!review)}>{allResolved?'Revisar cierre del día':'Revisar contabilización parcial'}</button>{review&&<div><p>Se guardará una solicitud local con los resultados actuales. Las misiones pendientes siguen abiertas. Con todas las misiones resueltas puedes completar el día sin esperar a mañana.</p><button disabled={busy||outcomes.every(o=>o.result==='pending')} onClick={()=>void save(()=>queueClose(day,outcomes.filter(o=>o.result!=='pending').map(o=>({id:`${day}:${o.m.id}`,day,mission:o.m.id,result:o.result,detail:'Vista previa local'})),objectives))}>{allResolved?'Confirmar cierre del día y sincronizar después':'Contabilizar misiones resueltas; el día sigue abierto'}</button></div>}</section>
 <details><summary>Registros guardados de este día</summary>{entries.map(e=><section key={e.id}><p>{missions.find(m=>m.id===e.mission)?.name}: {e.quantity} {e.unit} · {e.occurredAt} {e.note}</p><EntryCorrection entry={e} entries={entries} decisions={decisions} evaluations={evaluations} account={account} objectives={objectives} onSaved={()=>setNotice("Corrección guardada localmente; sincroniza para confirmarla.")}/></section>)}{decisions.map(d=><p key={d.id}>{missions.find(m=>m.id===d.mission)?.name}: {labels[d.result]}</p>)}</details><details><summary>Libro de movimientos · XP y MC</summary>{movements.sort((a,b)=>b.accreditedAt.localeCompare(a.accreditedAt)).map(m=><p key={m.id}>{m.amount>0?'+':''}{m.amount} {m.resource.toUpperCase()} · {m.cause==='reversal'?'Reversión':m.cause==='purchase'?'Compra':'Misión'} · {new Date(m.accreditedAt).toLocaleString('es-CO',{timeZone:'America/Bogota'})}</p>)}</details></main>;
}
