import React from 'react';
import type { Session } from '@supabase/supabase-js';
import { supabase } from './supabase';
import { selectPlayerStorage } from './storage';
import { SyncPanel } from './SyncPanel';
export function AuthGate({children}:{children:React.ReactNode}){
 const [session,setSession]=React.useState<Session|null>(null),[ready,setReady]=React.useState(false),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');
 const [cachedPlayer,setCachedPlayer]=React.useState<string|null>(null),[online,setOnline]=React.useState(navigator.onLine);
 const [recovering,setRecovering]=React.useState(false),[authNotice,setAuthNotice]=React.useState('');
 React.useEffect(()=>{
 let alive=true;
 const recoverOffline=()=>{const id=localStorage.getItem('winter-arc-last-player');if(!navigator.onLine&&id&&/^[a-zA-Z0-9-]+$/.test(id)){selectPlayerStorage(id);setCachedPlayer(id);setReady(true);}};
 const apply=(next:Session|null)=>{if(!alive)return;if(next){selectPlayerStorage(next.user.id);localStorage.setItem('winter-arc-last-player',next.user.id);setCachedPlayer(next.user.id);}else recoverOffline();setSession(next);setReady(true);};
 const connection=()=>{setOnline(navigator.onLine);recoverOffline();if(navigator.onLine)void supabase.auth.getSession().then(({data})=>apply(data.session));};
 window.addEventListener('online',connection);window.addEventListener('offline',connection);recoverOffline();
 const {data:{subscription}}=supabase.auth.onAuthStateChange((event,next)=>{if(event==='PASSWORD_RECOVERY')setRecovering(true);apply(next);});
 void supabase.auth.getSession().then(({data,error})=>{if(error&&alive){recoverOffline();setError('No se pudo recuperar la sesión.');setReady(true);}else apply(data.session);});
 return()=>{alive=false;subscription.unsubscribe();window.removeEventListener('online',connection);window.removeEventListener('offline',connection);};
 },[]);
 if(!ready)return <main><h1>Winter Arc</h1><p role="status">Recuperando sesión…</p></main>;
 if(recovering&&session)return <main><h1>Elige una nueva contraseña</h1><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),password=String(f.get('password'));if(password!==String(f.get('confirm'))){setError('Las contraseñas no coinciden.');return;}setBusy(true);setError('');try{const {error}=await supabase.auth.updateUser({password});if(error)setError('No se pudo actualizar la contraseña. Abre un enlace vigente y reintenta con conexión.');else{setRecovering(false);setAuthNotice('Contraseña actualizada.');}}catch{setError('No se pudo conectar. Reintenta.');}finally{setBusy(false);}}}><label>Nueva contraseña<input name="password" type="password" autoComplete="new-password" minLength={8} required/></label><label>Repite la contraseña<input name="confirm" type="password" autoComplete="new-password" minLength={8} required/></label><button disabled={busy||!online}>Guardar contraseña</button>{error&&<p role="alert">{error}</p>}</form></main>;
 if(!session&&!(cachedPlayer&&!online))return <main><header>WINTER ARC ❄</header><h1>Accede como Player</h1><p className="muted">Usa tu cuenta de Player creada en Authentication de Supabase. Puede tener el mismo correo del administrador, pero es una cuenta de la aplicación independiente.</p><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');const {error}=await supabase.auth.signInWithPassword({email:String(form.get('email')),password:String(form.get('password'))});if(error)setError('No se pudo iniciar sesión. Comprueba correo y contraseña de Player, confirmación de cuenta y conexión.');setBusy(false);}}><label>Correo<input name="email" type="email" autoComplete="username" required/></label><label>Contraseña de Player<input name="password" type="password" autoComplete="current-password" minLength={8} required/></label>{error&&<p role="alert" className="error">{error}</p>}<button disabled={busy}>{busy?'Accediendo…':'Iniciar sesión'}</button></form><details><summary>Recuperar acceso por correo</summary><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError('');setAuthNotice('');try{const {error}=await supabase.auth.resetPasswordForEmail(String(f.get('recoveryEmail')),{redirectTo:window.location.origin});if(error)setError('No se pudo solicitar el enlace. Comprueba la conexión y la configuración de correo de Supabase.');else setAuthNotice('Si la cuenta existe y el correo está habilitado, recibirás un enlace para elegir otra contraseña.');}catch{setError('No se pudo conectar. Reintenta.');}finally{setBusy(false);}}}><label>Correo de Player<input name="recoveryEmail" type="email" autoComplete="email" required/></label><button disabled={busy||!online}>Solicitar enlace de recuperación</button></form><p className="muted">La entrega depende del correo y las redirecciones configuradas en Supabase.</p></details><p role="status">{authNotice}</p><p className="muted">Los registros técnicos de desarrollo no se transfieren a tu cuenta.</p></main>;
 return <React.Fragment key={session?.user.id||cachedPlayer!}><SyncPanel signingOut={busy} onSignOut={async()=>{setBusy(true);try{const {error}=await supabase.auth.signOut({scope:'local'});if(error)throw error;localStorage.removeItem('winter-arc-last-player');setCachedPlayer(null);setSession(null);}finally{setBusy(false);}}}/>{children}</React.Fragment>;
}
