import React from 'react';
import {DateInput} from './DateInput';
import {previewMission} from './domain/preview';
import {correctEntry} from './storage';
import {missions,progress} from './domain/game';
import type {Entry,Decision,Evaluation,Snapshot,Objectives} from './storage';
export function EntryCorrection({entry,entries,decisions,evaluations,account,objectives,onSaved}:{entry:Entry;entries:Entry[];decisions:Decision[];evaluations:Evaluation[];account:Snapshot|null;objectives:Objectives;onSaved:()=>void}){
 const [review,setReview]=React.useState<{original:Entry;corrected:Entry;reason:string}|null>(null),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false);
 const mission=missions.find(m=>m.id===entry.mission)!;
 const effect=(list:Entry[])=>{const preview=previewMission(mission,list,decisions,objectives);return {result:preview.result,...preview.effect};};
 const before=evaluations.find(e=>e.mission===entry.mission)||effect(entries),after=review?effect(entries.map(e=>e.id===entry.id?review.corrected:e)):before;
 const delta={xp:after.xp-before.xp,mc:after.mc-before.mc};
 return <details><summary>Corregir registro</summary><form onSubmit={e=>{e.preventDefault();setError('');const f=new FormData(e.currentTarget),ticket=account?.tickets?.find(t=>t.id===f.get('ticketId')),corrected={...entry,quantity:Number(f.get('quantity')),unit:String(f.get('unit')??entry.unit),note:String(f.get('note')??entry.note),occurredAt:String(f.get('occurredAt')??entry.occurredAt),...(entry.mission==='food'&&account?.entryCorrectionsEnabled?{ticketId:ticket?.id,mealAt:ticket?.assignedAt,mealLabel:ticket?.label}:{})},reason=String(f.get('reason')).trim();if(!Number.isSafeInteger(corrected.quantity)||corrected.quantity<0||corrected.occurredAt.slice(0,10)!==entry.day||!reason){setError('Revisa cantidad, fecha y motivo.');return;}setReview({original:{...entry},corrected,reason});}}>
 <label>Nueva cantidad (0 para anular)<input name="quantity" type="number" min="0" step="1" defaultValue={entry.quantity} required/></label><label>Unidad o porción<input disabled={!account?.entryCorrectionsEnabled} name="unit" defaultValue={entry.unit} maxLength={100} required/></label><label>Fecha y hora en Bogotá<DateInput disabled={!account?.entryCorrectionsEnabled} name="occurredAt" type="datetime-local" defaultValue={entry.occurredAt} required/></label><label>Nota<textarea disabled={!account?.entryCorrectionsEnabled} name="note" defaultValue={entry.note} maxLength={2000}/></label>{entry.mission==='food'&&account?.entryCorrectionsEnabled&&<label>Cobertura<select name="ticketId" defaultValue={entry.ticketId||''}><option value="">Sin ticket</option>{account.tickets?.filter(t=>t.product==='food'&&t.assignedAt.startsWith(entry.day)).map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>}<label>Motivo de corrección<textarea name="reason" maxLength={2000} required/></label><button disabled={busy}>Comparar antes de guardar</button></form>
 {review&&<section aria-label="Comparación de corrección"><h3>Anterior → propuesto</h3><p>{review.original.quantity} {review.original.unit} → {review.corrected.quantity} {review.corrected.unit}</p><p>{review.original.occurredAt} → {review.corrected.occurredAt}</p><p>Cobertura: {review.original.mealLabel||'Sin ticket'} → {review.corrected.mealLabel||'Sin ticket'}</p><p>Nota: {review.original.note||'Sin nota'} → {review.corrected.note||'Sin nota'}</p><p>Resultado: {before.result} → {after.result}. Diferencia provisional: {delta.xp} XP / {delta.mc} MC.</p>{evaluations.some(e=>e.mission===entry.mission)&&<p>Si cambia el efecto: reversión de {before.xp} XP / {before.mc} MC y nueva acreditación de {after.xp} XP / {after.mc} MC. Nivel previsto: {progress(Math.max(0,(account?.balances?.xp||0)+delta.xp)).level}.</p>}<p className="muted">El servidor valida el cambio, conserva auditoría y revierte únicamente los movimientos afectados. Los objetivos históricos se conservan.</p><button disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await correctEntry(entry.id,review.corrected,review.reason,review.original.revision);setReview(null);onSaved();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}}}>Confirmar corrección</button><button disabled={busy} onClick={()=>setReview(null)}>Volver a editar</button></section>}{error&&<p role="alert">{error}</p>}</details>;
}
