import React from 'react';
import {seasonStart,seasonEnd,shiftDay} from './domain/reports';
export function MissionDatePicker({value,today,disabled,onChange}:{value:string;today:string;disabled:boolean;onChange:(day:string)=>void}){
 const max=today<seasonEnd?today:seasonEnd;
 const [month,setMonth]=React.useState(value.slice(0,7)),[open,setOpen]=React.useState(false);
 const panel=React.useRef<HTMLDivElement>(null),trigger=React.useRef<HTMLButtonElement>(null);
 const id=React.useId();
 const date=new Date(month+'-01T12:00:00Z'),offset=(date.getUTCDay()+6)%7;
 const length=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth()+1,0)).getUTCDate();
 const format=(day:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('en-GB',{...options,timeZone:'UTC'}).format(new Date(day+'T12:00:00Z'));
 function changeMonth(amount:number){const next=new Date(month+'-01T12:00:00Z');next.setUTCMonth(next.getUTCMonth()+amount);setMonth(next.toISOString().slice(0,7));}
 function choose(day:string){if(disabled||day<seasonStart||day>max)return;onChange(day);panel.current?.hidePopover();trigger.current?.focus();}
 return <section className="mission-date" aria-label="Mission date"><span className="date-kicker">ADVENTURE LOG</span><div className="mission-date-row"><button className="date-step" aria-label="Previous day" disabled={disabled||value<=seasonStart} onClick={()=>choose(shiftDay(value,-1))}>‹</button><button ref={trigger} type="button" className="mission-date-trigger" aria-expanded={open} aria-controls={id} aria-haspopup="dialog" disabled={disabled} onClick={()=>{if(!open)setMonth(value.slice(0,7));panel.current?.togglePopover();}}><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 5h14v15H5ZM8 3v4m8-4v4M5 10h14m-10 4h2m3 0h2m-8 3h2"/></svg><span><strong>{value===today?'Today':format(value,{weekday:'long'})}</strong><small>{format(value,{day:'numeric',month:'long',year:'numeric'})}</small></span><svg className="date-chevron" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button><button className="date-step" aria-label="Next day" disabled={disabled||value>=max} onClick={()=>choose(shiftDay(value,1))}>›</button></div><div ref={panel} id={id} popover="auto" role="dialog" aria-label="Choose a mission date" className="mission-calendar" onToggle={e=>setOpen(e.newState==='open')}><div className="mission-calendar-heading"><button className="date-step" aria-label="Previous month" disabled={month<=seasonStart.slice(0,7)} onClick={()=>changeMonth(-1)}>‹</button><h2 aria-live="polite">{format(month+'-01',{month:'long',year:'numeric'})}</h2><button className="date-step" aria-label="Next month" disabled={month>=max.slice(0,7)} onClick={()=>changeMonth(1)}>›</button></div><div className="mission-calendar-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span className="mission-weekday" key={d}>{d}</span>)}{Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{Array.from({length},(_,i)=>{const day=`${month}-${String(i+1).padStart(2,'0')}`,available=day>=seasonStart&&day<=max;return <button key={day} disabled={disabled||!available} aria-pressed={value===day} aria-current={day===today?'date':undefined} aria-label={format(day,{weekday:'long',day:'numeric',month:'long',year:'numeric'})} className="mission-calendar-day" onClick={()=>choose(day)}>{i+1}{day===today&&<span className="today-mark" aria-hidden="true"/>}</button>;})}</div><div className="mission-calendar-footer"><span>Past days and today only</span><button disabled={disabled||today<seasonStart||today>seasonEnd} onClick={()=>choose(today)}>Today</button></div></div></section>;
}
