import React from 'react';
import {liveQuery} from 'dexie';
import {db,localDay,weekStart} from './storage';
import type {Snapshot,Entry,Decision,Operation} from './storage';
import {missions,progress,levelThreshold} from './domain/game';
import {dates,daySummary,missionCounts,sleepCounts,ledgerTotals,seasonMaximum,seasonStart,seasonEnd,shiftDay} from './domain/reports';
const resultNames={fulfilled:'Cumplida',failed:'Incumplida',ticket:'Ticket',exempt:'Exenta',pending:'Pendiente'};
const statusNames:Record<string,string>={future:'Próximo',unsynced:'Por sincronizar',complete:'Completo',partial:'Parcial',pending:'Pendiente'};
function useReports(){
 const [data,setData]=React.useState<{account:Snapshot|null;entries:Entry[];decisions:Decision[];ops:Operation[]}>({account:null,entries:[],decisions:[],ops:[]});
 const [error,setError]=React.useState('');
 React.useEffect(()=>{const sub=liveQuery(async()=>({account:(await db.meta.get('account'))?.value||null,entries:await db.entries.toArray(),decisions:await db.decisions.toArray(),ops:await db.operations.toArray()})).subscribe({next:setData,error:()=>setError('No se pudo consultar el historial local.')});return()=>sub.unsubscribe();},[]);return {...data,error};
}
function readableDetail(decision:Decision){try{const detail=JSON.parse(decision.detail);if(decision.mission==='sleep')return `${detail.bedAt||detail.bed||'—'} → ${detail.wakeAt||detail.wake||'—'} · ${detail.minutes??'—'} minutos efectivos · ${detail.coverage==='flexible'?'Noche flexible':detail.coverage==='ticket'?'Ticket':'Horario estricto'}${detail.note?' · '+detail.note:''}`;return [detail.coach,detail.note].filter(Boolean).join(' · ');}catch{return decision.detail;}}
export function Ledger({account,day}:{account:Snapshot|null;day?:string}){
 const movements=(account?.movements||[]).filter(m=>!day||m.day===day).sort((a,b)=>b.accreditedAt.localeCompare(a.accreditedAt)||b.id.localeCompare(a.id));
 return <details><summary>{day?'Movimientos del día':'Libro de movimientos · XP y MC'}</summary>{day&&!account?.historyEnabled&&<p className="muted">Aplica la migración 006 y sincroniza para consultar el origen por día.</p>}{!movements.length&&<p className="muted">Sin movimientos confirmados en esta vista.</p>}{movements.map(m=><section className="mission" key={m.id}><strong>{m.amount>0?'+':''}{m.amount} {m.resource.toUpperCase()}</strong><p>{m.cause==='reversal'?'Reversión':m.cause==='purchase'?'Compra':'Misión'}{m.mission?' · '+missions.find(x=>x.id===m.mission)?.name:''}{m.label?' · '+m.label:''}</p><p className="muted">{m.day?'Día '+m.day+' · ':''}{new Date(m.accreditedAt).toLocaleString('es-CO',{timeZone:'America/Bogota'})} · Bogotá</p>{m.reversesId&&<p className="muted">Revierte movimiento {m.reversesId}</p>}</section>)}</details>;
}
export function History({onEdit}:{onEdit:(day:string)=>void}){
 const {account,entries,decisions,ops,error}=useReports(),today=localDay();
 const [month,setMonth]=React.useState(today.slice(0,7)>='2026-10'&&today.slice(0,7)<='2026-12'?today.slice(0,7):'2026-10');
 const [selected,setSelected]=React.useState(today<seasonStart?seasonStart:today>seasonEnd?seasonEnd:today);
 const [mode,setMode]=React.useState<'calendar'|'list'>('calendar');
 const all=dates().filter(d=>d.startsWith(month)),evaluation=account?.evaluations||[],summary=daySummary(selected,evaluation,ops,today),objectives=account?.days?.find(d=>d.day===selected);
 const offset=(new Date(all[0]+'T12:00Z').getUTCDay()+6)%7;
 return <section><h1>Historial</h1>{error&&<p role="alert">{error}</p>}<p className="muted">Resultados confirmados de la temporada. Los cambios locales por sincronizar se señalan aparte.</p><label>Mes<select value={month} onChange={e=>{setMonth(e.target.value);setSelected(dates().find(d=>d.startsWith(e.target.value))!);}}><option value="2026-10">Octubre</option><option value="2026-11">Noviembre</option><option value="2026-12">Diciembre</option></select></label><div className="actions"><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}>Calendario</button><button aria-pressed={mode==='list'} onClick={()=>setMode('list')}>Lista</button></div><p className="muted">Completo: {missions.length} resultados definitivos · Parcial: algunas misiones contabilizadas · Pendiente: sin cierre confirmado.</p>
 <div className={mode==='calendar'?'calendar':'history-list'}>{mode==='calendar'&&['L','M','X','J','V','S','D'].map((d,i)=><span className="weekday" key={i}>{d}</span>)}{mode==='calendar'&&Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{all.map(day=>{const s=daySummary(day,evaluation,ops,today);return <button className={'day-cell '+s.status} key={day} aria-pressed={selected===day} aria-label={`${day}: ${statusNames[s.status]}, ${s.confirmed} de ${missions.length} contabilizadas${s.tickets?', con ticket':''}${s.exempt?', con exención':''}`} onClick={()=>setSelected(day)}><strong>{mode==='calendar'?Number(day.slice(8)):day}</strong><small>{statusNames[s.status]}</small>{(s.tickets>0||s.exempt>0)&&<small>{s.tickets?'T':''}{s.exempt?' E':''}</small>}</button>;})}</div>
 <section className="hero editor"><h2>{selected} · {statusNames[summary.status]}</h2><p>{summary.confirmed} / {missions.length} misiones contabilizadas · {summary.xp} XP · {summary.mc>=0?'+':''}{summary.mc} MC de misiones</p>{summary.dirty&&<p role="status">Hay cambios pendientes de confirmar; los resultados de abajo son los últimos aceptados.</p>}<p className="muted">Objetivos {objectives?.objectives.status==='verified'?'históricos verificados':'pendientes de verificar'}{objectives?' · rango '+objectives.objectives.rank:''}{objectives?.ruleVersion?' · reglas '+objectives.ruleVersion:''}</p>{objectives&&<p className="muted">Ejercicios: {objectives.objectives.pushups} flexiones / {objectives.objectives.abs} abdominales / {objectives.objectives.squats} sentadillas · {objectives.objectives.steps} pasos · {objectives.objectives.reading} páginas</p>}
 {missions.map(m=>{const result=evaluation.find(e=>e.day===selected&&e.mission===m.id);return <div className="mission row" key={m.id}><span>{m.name}</span><span>{resultNames[result?.result||'pending']}{result?' · '+result.xp+' XP / '+result.mc+' MC':''}</span></div>;})}
 <button disabled={selected>today} onClick={()=>onEdit(selected)}>Completar o corregir este día</button>
 <details><summary>Registros y notas del día</summary>{entries.filter(e=>e.day===selected).map(e=><p key={e.id}>{missions.find(m=>m.id===e.mission)?.name}: {e.quantity} {e.unit} · {e.occurredAt.replace('T',' ')}{e.ticketId?' · Ticket de '+e.mealLabel:''}{e.note?' · '+e.note:''}</p>)}{decisions.filter(d=>d.day===selected).map(d=><p key={d.id}>{missions.find(m=>m.id===d.mission)?.name}: {resultNames[d.result]} · {readableDetail(d)}</p>)}</details><Ledger account={account} day={selected}/></section></section>;
}
export function Progress({provisional,day}:{provisional:{xp:number;mc:number};day:string}){
 const {account,ops,error}=useReports(),today=localDay(),player=progress(account?.balances?.xp||0);
 const [week,setWeek]=React.useState(weekStart(today)>=seasonStart&&weekStart(today)<=seasonEnd?weekStart(today):seasonStart);
 const end=shiftDay(week,6)>seasonEnd?seasonEnd:shiftDay(week,6),elapsed=dates(week,end).filter(d=>d<=today),evaluations=account?.evaluations||[];
 const sleep=sleepCounts(elapsed,evaluations,account?.decisions||[]),totals=ledgerTotals(account?.movements||[]),ranks=[{rank:'D',level:1,reps:10,steps:1000,pages:10},{rank:'C',level:4,reps:20,steps:2000,pages:15},{rank:'B',level:7,reps:50,steps:5000,pages:25},{rank:'A',level:10,reps:75,steps:7500,pages:35},{rank:'S',level:13,reps:100,steps:10000,pages:45}],next=ranks.find(r=>r.level>player.level);
 const unresolved=ops.filter(o=>['pending','conflict'].includes(o.status)&&o.kind!=='conflict-resolution').length;
 return <section><h1>Progreso</h1>{error&&<p role="alert">{error}</p>}<section className="hero"><div className="row"><strong>{account?.balances?.xp??'—'} XP</strong><span className="badge">Rango {player.rank} · Nivel {player.level}</span></div><progress value={player.current} max={player.next} aria-label="Avance de XP del nivel"/><p>{player.next-player.current} XP para nivel {player.level+1}</p><p className="muted">{account?.balances?.xp||0} / {seasonMaximum} XP del máximo ordinario de 88 días. Los tickets y exenciones reducen los premios disponibles.</p>{next&&<p>Siguiente rango: {next.rank} · nivel {next.level} · faltan {levelThreshold(next.level)-(account?.balances?.xp||0)} XP.</p>}</section><p className="muted">Cambio provisional del {day}: {provisional.xp>=0?'+':''}{provisional.xp} XP / {provisional.mc>=0?'+':''}{provisional.mc} MC. {unresolved} operaciones por confirmar; no se suman al saldo disponible.</p>
 <details><summary>Exigencias por rango</summary><div className="table-scroll"><table><thead><tr><th>Rango</th><th>Nivel</th><th>Reps. por ejercicio</th><th>Pasos</th><th>Páginas</th></tr></thead><tbody>{ranks.map(r=><tr key={r.rank}><td>{r.rank}</td><td>{r.level}</td><td>{r.reps}</td><td>{r.steps}</td><td>{r.pages}</td></tr>)}</tbody></table></div><p className="muted">Los cambios de nivel afectan los objetivos desde el día siguiente a su acreditación; los días anteriores conservan sus objetivos.</p></details>
 <h2>Cumplimiento semanal</h2><label>Semana<select value={week} onChange={e=>setWeek(e.target.value)}>{dates().filter(d=>new Date(d+'T12:00Z').getUTCDay()===1).map(d=><option key={d} value={d}>Desde {d}{d==='2026-12-28'?' · parcial':''}</option>)}</select></label><p className="muted">{week} → {end} · {elapsed.length} días transcurridos de {dates(week,end).length}.{today<end?' Semana en curso; resultado incompleto.':''}{dates(week,end).length<7?' Semana parcial de temporada.':''}</p>
 <div className="table-scroll"><table><thead><tr><th>Misión</th><th>Cumplidas</th><th>Fallos</th><th>Tickets</th><th>Exentas</th><th>Pendientes</th></tr></thead><tbody>{missions.map(m=>{const c=missionCounts(m.id,elapsed,evaluations);return <tr key={m.id}><th>{m.name}</th><td>{c.fulfilled}{elapsed.length>0?' / '+elapsed.length+' ('+Math.round(c.fulfilled/elapsed.length*100)+'%)':''}</td><td>{c.failed}</td><td>{c.ticket}</td><td>{c.exempt}</td><td>{c.pending}</td></tr>;})}</tbody></table></div>
 <section className="hero editor"><h2>Descanso de la semana</h2><p>Horario estricto cumplido: {sleep.strict} / {sleep.registered} noches contabilizadas.</p><p className="muted">Flexibles: {sleep.flexible} · Con ticket: {sleep.ticket} · Incumplidas: {sleep.failed} · Exentas: {sleep.exempt} · Pendientes: {sleep.pending}</p><p className="muted">Las coberturas flexible y ticket se muestran aunque falte sueño efectivo; ese incumplimiento aparece también en el contador de fallos. Las exenciones no entran en noches evaluadas.</p></section>
 <section className="hero"><h2>Monedas</h2><strong>{account?.balances?.mc??'—'} MC{(account?.balances?.mc||0)<0?' · deuda':''}</strong><p className="muted">Premios: +{totals.rewards} · Sanciones: {totals.penalties} · Compras: {totals.purchases} · Reversiones netas: {totals.reversals}</p></section><Ledger account={account}/></section>;
}
