import React from 'react';
import {RpgSelect} from './RpgSelect';
import {liveQuery} from 'dexie';
import {db,localDay,isDayClosed,weekStart} from './storage';
import type {Snapshot,Entry,Decision,Operation} from './storage';
import {missions,progress,levelThreshold} from './domain/game';
import {dates,daySummary,missionCounts,sleepCounts,ledgerTotals,seasonMaximum,seasonStart,seasonEnd,shiftDay} from './domain/reports';
const resultNames={fulfilled:'Completed',failed:'Failed',ticket:'Ticket',exempt:'Exempt',pending:'Pending'};
const statusNames:Record<string,string>={future:'Upcoming',unsynced:'Awaiting sync',complete:'Complete',partial:'Partial',pending:'Pending'};
function useReports(){
 const [data,setData]=React.useState<{account:Snapshot|null;entries:Entry[];decisions:Decision[];ops:Operation[]}>({account:null,entries:[],decisions:[],ops:[]});
 const [error,setError]=React.useState('');
 React.useEffect(()=>{const sub=liveQuery(async()=>({account:(await db.meta.get('account'))?.value||null,entries:await db.entries.toArray(),decisions:await db.decisions.toArray(),ops:await db.operations.toArray()})).subscribe({next:setData,error:()=>setError('Could not load local history.')});return()=>sub.unsubscribe();},[]);return {...data,error};
}
function readableDetail(decision:Decision){try{const detail=JSON.parse(decision.detail);if(decision.mission==='sleep'&&detail.selfReported)return `Self-reported · ${detail.coverage==='flexible'?'Flexible night':detail.coverage==='ticket'?'Ticket':'Strict schedule'}${detail.minimumSleepMet?' · 7+ hours confirmed':''}`;if(decision.mission==='sleep')return `${detail.bedAt||detail.bed||'—'} → ${detail.wakeAt||detail.wake||'—'} · ${detail.minutes??'—'} actual minutes slept · ${detail.coverage==='flexible'?'Flexible night':detail.coverage==='ticket'?'Ticket':'Strict schedule'}${detail.note?' · '+detail.note:''}`;return [detail.coach,detail.note].filter(Boolean).join(' · ');}catch{return decision.detail;}}
export function Ledger({account,day}:{account:Snapshot|null;day?:string}){
 const movements=(account?.movements||[]).filter(m=>!day||m.day===day).sort((a,b)=>b.accreditedAt.localeCompare(a.accreditedAt)||b.id.localeCompare(a.id));
 return <details><summary>{day?'Daily transactions':'Transaction ledger · XP and MC'}</summary>{day&&!account?.historyEnabled&&<p className="muted">Apply migration 006 and sync to view the source by day.</p>}{!movements.length&&<p className="muted">No confirmed transactions in this view.</p>}{movements.map(m=><section className="mission" key={m.id}><strong>{m.amount>0?'+':''}{m.amount} {m.resource.toUpperCase()}</strong><p>{m.cause==='reversal'?'Reversal':m.cause==='purchase'?'Purchase':'Mission'}{m.mission?' · '+missions.find(x=>x.id===m.mission)?.name:''}{m.label?' · '+m.label:''}</p><p className="muted">{m.day?'Day '+m.day+' · ':''}{new Date(m.accreditedAt).toLocaleString('en-GB',{timeZone:'America/Bogota'})} · Bogotá</p>{m.reversesId&&<p className="muted">Reverses transaction {m.reversesId}</p>}</section>)}</details>;
}
export function History({onEdit}:{onEdit:(day:string)=>void}){
 const {account,entries,decisions,ops,error}=useReports(),today=localDay();
 const [month,setMonth]=React.useState(today.slice(0,7)>='2026-10'&&today.slice(0,7)<='2026-12'?today.slice(0,7):'2026-10');
 const [selected,setSelected]=React.useState(today<seasonStart?seasonStart:today>seasonEnd?seasonEnd:today);
 const [mode,setMode]=React.useState<'calendar'|'list'>('calendar');
 const all=dates().filter(d=>d.startsWith(month)),evaluation=account?.evaluations||[],summary=daySummary(selected,evaluation,ops,today),objectives=account?.days?.find(d=>d.day===selected);
 const offset=(new Date(all[0]+'T12:00Z').getUTCDay()+6)%7;
 return <section><h1>History</h1>{error&&<p role="alert">{error}</p>}<p className="muted">Confirmed season results. Local changes awaiting sync are marked separately.</p><label>Month<RpgSelect value={month} onChange={e=>{setMonth(e.target.value);setSelected(dates().find(d=>d.startsWith(e.target.value))!);}}><option value="2026-10">October</option><option value="2026-11">November</option><option value="2026-12">December</option></RpgSelect></label><div className="actions"><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}>Calendar</button><button aria-pressed={mode==='list'} onClick={()=>setMode('list')}>List</button></div><p className="muted">Complete: {missions.length} final results · Partial: some missions accounted for · Pending: no confirmed closure.</p>
 <div className={mode==='calendar'?'calendar':'history-list'}>{mode==='calendar'&&['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((d,i)=><span className="weekday" key={i}>{d}</span>)}{mode==='calendar'&&Array.from({length:offset},(_,i)=><span key={'blank'+i}/>)}{all.map(day=>{const s=daySummary(day,evaluation,ops,today);return <button className={'day-cell '+s.status} key={day} aria-pressed={selected===day} aria-label={`${day}: ${statusNames[s.status]}, ${s.confirmed} of ${missions.length} accounted for${s.tickets?', with ticket':''}${s.exempt?', with exemption':''}`} onClick={()=>setSelected(day)}><strong>{mode==='calendar'?Number(day.slice(8)):day}</strong><small>{statusNames[s.status]}</small>{(s.tickets>0||s.exempt>0)&&<small>{s.tickets?'T':''}{s.exempt?' E':''}</small>}</button>;})}</div>
 <section className="hero editor"><h2>{selected} · {statusNames[summary.status]}</h2><p>{summary.confirmed} / {missions.length} missions accounted for · {summary.xp} XP · {summary.mc>=0?'+':''}{summary.mc} MC from missions</p>{summary.dirty&&<p role="status">Some changes are awaiting confirmation; the results below are the latest accepted results.</p>}<p className="muted">Targets {objectives?.objectives.status==='verified'?'historically verified':'awaiting verification'}{objectives?' · rank '+objectives.objectives.rank:''}{objectives?.ruleVersion?' · rules '+objectives.ruleVersion:''}</p>{objectives&&<p className="muted">Exercises: {objectives.objectives.pushups} push-ups / {objectives.objectives.abs} crunches / {objectives.objectives.squats} squats · {objectives.objectives.steps} steps · {objectives.objectives.reading} pages</p>}
 {missions.map(m=>{const result=evaluation.find(e=>e.day===selected&&e.mission===m.id);return <div className="mission row" key={m.id}><span>{m.name}</span><span>{resultNames[result?.result||'pending']}{result?' · '+result.xp+' XP / '+result.mc+' MC':''}</span></div>;})}
 <button disabled={selected>today} onClick={()=>onEdit(selected)}>{isDayClosed(selected,today)?'View closed day':'Complete or correct this day'}</button>
 <details><summary>Daily records and notes</summary>{entries.filter(e=>e.day===selected).map(e=><p key={e.id}>{missions.find(m=>m.id===e.mission)?.name}: {e.quantity} {e.unit} · {e.occurredAt.replace('T',' ')}{e.ticketId?' · Ticket for '+e.mealLabel:''}{e.note?' · '+e.note:''}</p>)}{decisions.filter(d=>d.day===selected).map(d=><p key={d.id}>{missions.find(m=>m.id===d.mission)?.name}: {resultNames[d.result]} · {readableDetail(d)}</p>)}</details><Ledger account={account} day={selected}/></section></section>;
}
export function Progress(){
 const {account,ops,error}=useReports(),today=localDay(),player=progress(account?.balances?.xp||0);
 const [week,setWeek]=React.useState(weekStart(today)>=seasonStart&&weekStart(today)<=seasonEnd?weekStart(today):seasonStart);
 const end=shiftDay(week,6)>seasonEnd?seasonEnd:shiftDay(week,6),elapsed=dates(week,end).filter(d=>d<=today),evaluations=account?.evaluations||[];
 const sleep=sleepCounts(elapsed,evaluations,account?.decisions||[]),totals=ledgerTotals(account?.movements||[]),ranks=[{rank:'D',level:1,reps:10,steps:1000,pages:10},{rank:'C',level:4,reps:20,steps:2000,pages:15},{rank:'B',level:7,reps:50,steps:5000,pages:25},{rank:'A',level:10,reps:75,steps:7500,pages:35},{rank:'S',level:13,reps:100,steps:10000,pages:45}],next=ranks.find(r=>r.level>player.level);
 return <section><h1>Progress</h1>{error&&<p role="alert">{error}</p>}<section className="hero"><div className="row"><strong>{account?.balances?.xp??'—'} XP</strong><span className="badge">Rank {player.rank} · Level {player.level}</span></div><progress value={player.current} max={player.next} aria-label="Level XP progress"/><p>{player.next-player.current} XP to level {player.level+1}</p><p className="muted">{account?.balances?.xp||0} / {seasonMaximum} XP of the standard 88-day maximum. Tickets and exemptions reduce available rewards.</p>{next&&<p>Next rank: {next.rank} · level {next.level} · remaining {levelThreshold(next.level)-(account?.balances?.xp||0)} XP.</p>}</section>
 <details><summary>Rank requirements</summary><div className="table-scroll"><table><thead><tr><th>Rank</th><th>Level</th><th>Reps per exercise</th><th>Steps</th><th>Pages</th></tr></thead><tbody>{ranks.map(r=><tr key={r.rank}><td>{r.rank}</td><td>{r.level}</td><td>{r.reps}</td><td>{r.steps}</td><td>{r.pages}</td></tr>)}</tbody></table></div><p className="muted">Level changes affect targets starting the day after they are credited; previous days keep their original targets.</p></details>
 <h2>Weekly completion</h2><label>Week<RpgSelect value={week} onChange={e=>setWeek(e.target.value)}>{dates().filter(d=>new Date(d+'T12:00Z').getUTCDay()===1).map(d=><option key={d} value={d}>From {d}{d==='2026-12-28'?' · partial':''}</option>)}</RpgSelect></label><p className="muted">{week} → {end} · {elapsed.length} days elapsed out of {dates(week,end).length}.{today<end?' Week in progress; results are incomplete.':''}{dates(week,end).length<7?' Partial season week.':''}</p>
 <div className="table-scroll"><table><thead><tr><th>Mission</th><th>Completed</th><th>Failures</th><th>Tickets</th><th>Exempt</th><th>Pending</th></tr></thead><tbody>{missions.map(m=>{const c=missionCounts(m.id,elapsed,evaluations);return <tr key={m.id}><th>{m.name}</th><td>{c.fulfilled}{elapsed.length>0?' / '+elapsed.length+' ('+Math.round(c.fulfilled/elapsed.length*100)+'%)':''}</td><td>{c.failed}</td><td>{c.ticket}</td><td>{c.exempt}</td><td>{c.pending}</td></tr>;})}</tbody></table></div>
 <section className="hero editor"><h2>Weekly sleep</h2><p>Strict schedule met: {sleep.strict} / {sleep.registered} nights accounted for.</p><p className="muted">Flexible: {sleep.flexible} · With ticket: {sleep.ticket} · Failed: {sleep.failed} · Exempt: {sleep.exempt} · Pending: {sleep.pending}</p><p className="muted">Flexible nights and ticket coverage are shown even when actual sleep is insufficient; those failures also appear in the failure count. Exemptions are excluded from evaluated nights.</p></section>
 <section className="hero"><h2>Coins</h2><strong>{account?.balances?.mc??'—'} MC{(account?.balances?.mc||0)<0?' · debt':''}</strong><p className="muted">Rewards: +{totals.rewards} · Penalties: {totals.penalties} · Purchases: {totals.purchases} · Net reversals: {totals.reversals}</p></section><Ledger account={account}/></section>;
}
