import React from 'react';
type Option={value:string;label:string;disabled:boolean};
function textOf(node:React.ReactNode):string{return React.Children.toArray(node).map(child=>React.isValidElement<{children?:React.ReactNode}>(child)?textOf(child.props.children):String(child)).join('');}
function optionsOf(children:React.ReactNode):Option[]{return React.Children.toArray(children).flatMap(child=>{if(!React.isValidElement<{value?:string;disabled?:boolean;children?:React.ReactNode}>(child))return [];if(child.type==='option')return [{value:String(child.props.value??textOf(child.props.children)),label:textOf(child.props.children),disabled:!!child.props.disabled}];return optionsOf(child.props.children);});}
export function RpgSelect({children,value,defaultValue,onChange,disabled,...props}:React.ComponentProps<'select'>){
 const options=optionsOf(children),[draft,setDraft]=React.useState(String(defaultValue??options[0]?.value??'')),[open,setOpen]=React.useState(false);
 const selected=String(value??draft),current=options.find(o=>o.value===selected)||options[0];
 const native=React.useRef<HTMLSelectElement>(null),trigger=React.useRef<HTMLButtonElement>(null),panel=React.useRef<HTMLDivElement>(null),id=React.useId();
 const [position,setPosition]=React.useState<React.CSSProperties>({});
 function close(focus=true){panel.current?.hidePopover();if(focus)trigger.current?.focus();}
 function choose(option:Option){if(disabled||option.disabled)return;const select=native.current!;select.value=option.value;select.dispatchEvent(new Event('change',{bubbles:true}));close();}
 function show(){if(open){close();return;}const rect=trigger.current!.getBoundingClientRect(),below=window.innerHeight-rect.bottom-12,above=rect.top-12,up=below<160&&above>below,height=Math.min(280,Math.max(80,up?above:below));setPosition({left:rect.left,width:rect.width,maxHeight:height,...(up?{bottom:window.innerHeight-rect.top+6,top:'auto'}:{top:rect.bottom+6,bottom:'auto'})});panel.current?.showPopover();requestAnimationFrame(()=>{const buttons=panel.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)');const active=panel.current?.querySelector<HTMLButtonElement>('[aria-selected="true"]:not(:disabled)');(active||buttons?.[0])?.focus();});}
 React.useEffect(()=>{if(!open)return;const dismiss=()=>close(false);window.addEventListener('resize',dismiss);const scroll=(e:Event)=>{if(e.target!==panel.current&&!panel.current?.contains(e.target as Node))dismiss();};document.addEventListener('scroll',scroll,true);return()=>{window.removeEventListener('resize',dismiss);document.removeEventListener('scroll',scroll,true);};},[open]);
 return <span className="rpg-select"><select {...props} ref={native} value={value} defaultValue={value===undefined?defaultValue:undefined} disabled={disabled} className="rpg-select-native" tabIndex={-1} aria-hidden="true" onChange={e=>{setDraft(e.target.value);onChange?.(e);}}>{children}</select><button ref={trigger} type="button" className="rpg-select-trigger" disabled={disabled} role="combobox" aria-expanded={open} aria-controls={id} aria-haspopup="listbox" aria-label={props['aria-label']||props.name||undefined} onClick={show} onKeyDown={e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();show();}}}><span>{current?.label}</span><svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="m6 9 6 6 6-6"/></svg></button><div ref={panel} id={id} popover="auto" role="listbox" className="rpg-select-options" style={position} onToggle={e=>setOpen(e.newState==='open')} onKeyDown={e=>{const buttons=Array.from(panel.current!.querySelectorAll<HTMLButtonElement>('button:not(:disabled)')),index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:(index+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close();}if(e.key==='Tab')close(false);}}>{options.map(o=><button type="button" role="option" aria-selected={o.value===current?.value} key={o.value} disabled={o.disabled} onClick={()=>choose(o)}><span>{o.label}</span><svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m3 8 3 3 7-7"/></svg></button>)}</div></span>;
}
