import React from 'react';
import {RpgSelect} from './RpgSelect';
import {liveQuery} from 'dexie';
import {db,correctEntry,setDecision} from './storage';
import type {Entry,Decision} from './storage';
import {createBackup,previewBackup,restoreBackup,historyCSV} from './backup';
import type {Backup,RestoreReview} from './backup';
import {pwaStatus,pwaRegistration,installPrompt,requestInstall} from './pwa';
function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function describe(value:RestoreReview['value']){if('quantity' in value)return `${value.day} · ${value.mission}: ${value.quantity} ${value.unit}`;if('result' in value)return `${value.day} · ${value.mission}: ${value.result}`;return `${value.day} · ${value.kind}`;}
export function Tools({canUpdate}:{canUpdate:boolean}){
 const [status,setStatus]=React.useState(''),[busy,setBusy]=React.useState(false),[preview,setPreview]=React.useState<{backup:Backup;newRecords:number;identical:number;conflicts:number}|null>(null),[reviews,setReviews]=React.useState<RestoreReview[]>([]),[currentValues,setCurrentValues]=React.useState<Record<string,RestoreReview['value']|undefined>>({}),[pwa,setPwa]=React.useState(pwaStatus),[online,setOnline]=React.useState(navigator.onLine);
 React.useEffect(()=>{const update=()=>{setPwa(pwaStatus);setOnline(navigator.onLine);};window.addEventListener('winter-arc-pwa',update);window.addEventListener('online',update);window.addEventListener('offline',update);const sub=liveQuery(()=>db.restores.where('status').equals('pending').toArray()).subscribe(rows=>{setReviews(rows);void Promise.all(rows.map(async r=>[r.id,await db[r.type].get(r.value.id)] as const)).then(values=>setCurrentValues(Object.fromEntries(values)));});return()=>{sub.unsubscribe();window.removeEventListener('winter-arc-pwa',update);window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(error){setStatus(error instanceof Error?error.message:'Could not complete the operation.');}finally{setBusy(false);}}
 return <section><h1>Backup and installation</h1><p role="status">{status}</p><section className="hero"><h2>Backup</h2><p className="muted">Includes this account's records, decisions, history, operations and transactions. Store the file privately. It contains no passwords or session credentials.</p><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{const backup=await createBackup();download(JSON.stringify(backup,null,2),`winter-arc-${backup.exportedAt.slice(0,10)}.json`,'application/json');setStatus('JSON backup ready to download.');})}>Download JSON backup</button><button disabled={busy} onClick={()=>void action(async()=>{const backup=await createBackup();download(historyCSV(backup),`winter-arc-history-${backup.exportedAt.slice(0,10)}.csv`,'text/csv;charset=utf-8');setStatus('Readable history ready to download.');})}>Download history CSV</button></div><label>Review a backup from this account<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];setPreview(null);if(file)void action(async()=>{if(file.size>20*1024*1024)throw new Error('The backup exceeds the 20 MB size limit.');const result=await previewBackup(JSON.parse(await file.text()));setPreview(result);setStatus('Backup validated. Review the summary before restoring.');});}}/></label>{preview&&<section><p>Backup from {new Date(preview.backup.exportedAt).toLocaleString('en-GB')} · {preview.newRecords} new · {preview.identical} matching · {preview.conflicts} differences to review.</p><p className="muted">Only missing data will be added. Differences are preserved for review. Restored original operations will be verified with Supabase during sync; a backup balance cannot be used for purchases until confirmed.</p><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{const result=await restoreBackup(preview.backup);setPreview(null);setStatus(`Restore complete: ${result.newRecords} new, ${result.identical} matching and ${result.conflicts} differences. Sync to verify the remote copy.`);})}>Restore missing data</button><button disabled={busy} onClick={()=>setPreview(null)}>Cancel review</button></div></section>}</section>
 {reviews.length>0&&<section className="hero editor"><h2>Backup differences · {reviews.length}</h2><p className="muted">Your current data was preserved. Any correction chosen here is audited and requires server confirmation.</p>{reviews.map(review=><details key={review.id}><summary>{describe(review.value)}</summary><p>Current value: {currentValues[review.id]?describe(currentValues[review.id]!):'No compatible local record exists.'}</p><p>Backup value: {describe(review.value)}</p><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),reason=String(form.get('reason')||'').trim();void action(async()=>{
 if(!reason)throw new Error('Explain the reason for the resolution.');
 if(form.get('choice')==='backup'){
  if(review.type==='entries'){const value=review.value as Entry,current=await db.entries.get(value.id);if(!current||['day','mission','unit','note','occurredAt'].some(k=>current[k as keyof Entry]!==value[k as keyof Entry]))throw new Error('Complete the correction in Missions: no compatible entry exists to correct only its quantity.');await correctEntry(value.id,value.quantity,reason);}
  else if(review.type==='decisions'){const value=review.value as Decision;if(!await db.decisions.get(value.id))throw new Error('Record the result in Missions to restore this decision, which has no original operation.');let detail:Record<string,unknown>;try{detail=JSON.parse(value.detail);}catch{detail={};}await setDecision({day:value.day,mission:value.mission,result:value.result,detail:JSON.stringify({...detail,note:reason})});}
  else throw new Error('Different operations require reviewing the record or closure in Missions; they cannot be executed from the backup.');
 }
 await db.restores.update(review.id,{status:form.get('choice')==='backup'?'corrected':'kept-local',reason,resolvedAt:new Date().toISOString()});setStatus('Resolution saved. Sync the corrections when you are online.');
 });}}><label>Resolution<RpgSelect name="choice"><option value="local">Keep current data</option>{review.type!=='operations'&&<option value="backup">Create a correction using the backup value</option>}</RpgSelect></label><label>Reason<input name="reason" required maxLength={2000}/></label><button disabled={busy}>Save resolution</button></form></details>)}</section>}
 <section className="hero editor"><h2>Install Winter Arc</h2><p role="status">{pwa}</p><p>{online?'Online':'Offline'} · Records are saved on this device; purchases and balance confirmation require an internet connection.</p>{installPrompt?<button onClick={()=>void action(async()=>{await requestInstall();})}>Install app</button>:<p className="muted">If your browser supports installation, use its “Install app” or “Add to Home Screen” menu. On iPhone: Share → Add to Home Screen.</p>}{pwaRegistration?.waiting&&<button disabled={!canUpdate||busy} onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>window.location.reload(),{once:true});pwaRegistration?.waiting?.postMessage({type:'ACTIVATE_UPDATE'});}}>Apply update</button>}{!canUpdate&&<p className="muted">Save or cancel your record form before updating.</p>}<p className="muted">The first launch requires an internet connection. After that, cached files and your records let you work offline. Installation button availability depends on your browser.</p></section></section>;
}
