import React from 'react';
import {liveQuery} from 'dexie';
import {db,correctEntry,setDecision} from './storage';
import type {Entry,Decision} from './storage';
import {createBackup,previewBackup,restoreBackup,historyCSV} from './backup';
import type {Backup,RestoreReview} from './backup';
import {pwaStatus,pwaRegistration,installPrompt,requestInstall} from './pwa';
function download(content:string,name:string,type:string){const url=URL.createObjectURL(new Blob([content],{type})),link=document.createElement('a');link.href=url;link.download=name;link.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000);}
function describe(value:RestoreReview['value']){if('quantity' in value)return `${value.day} · ${value.mission}: ${value.quantity} ${value.unit}`;if('result' in value)return `${value.day} · ${value.mission}: ${value.result}`;return `${value.day} · ${value.kind}`;}
export function Tools({canUpdate}:{canUpdate:boolean}){
 const [status,setStatus]=React.useState(''),[busy,setBusy]=React.useState(false),[preview,setPreview]=React.useState<{backup:Backup;newRecords:number;identical:number;conflicts:number}|null>(null),[reviews,setReviews]=React.useState<RestoreReview[]>([]),[currentValues,setCurrentValues]=React.useState<Record<string,RestoreReview['value']|undefined>>({}),[pwa,setPwa]=React.useState(pwaStatus),[online,setOnline]=React.useState(navigator.onLine);
 React.useEffect(()=>{const update=()=>{setPwa(pwaStatus);setOnline(navigator.onLine);};window.addEventListener('winter-arc-pwa',update);window.addEventListener('online',update);window.addEventListener('offline',update);const sub=liveQuery(()=>db.restores.where('status').equals('pending').toArray()).subscribe(rows=>{setReviews(rows);void Promise.all(rows.map(async r=>[r.id,await db[r.type].get(r.value.id)] as const)).then(values=>setCurrentValues(Object.fromEntries(values)));});return()=>{sub.unsubscribe();window.removeEventListener('winter-arc-pwa',update);window.removeEventListener('online',update);window.removeEventListener('offline',update);};},[]);
 async function action(fn:()=>Promise<void>){setBusy(true);try{await fn();}catch(error){setStatus(error instanceof Error?error.message:'No se pudo completar la operación.');}finally{setBusy(false);}}
 return <section><h1>Respaldo e instalación</h1><p role="status">{status}</p><section className="hero"><h2>Copia de seguridad</h2><p className="muted">Incluye registros, decisiones, historial, operaciones y movimientos de esta cuenta. Guarda el archivo en un lugar privado. No contiene contraseñas ni credenciales de sesión.</p><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{const backup=await createBackup();download(JSON.stringify(backup,null,2),`winter-arc-${backup.exportedAt.slice(0,10)}.json`,'application/json');setStatus('Copia JSON preparada para descargar.');})}>Descargar copia JSON</button><button disabled={busy} onClick={()=>void action(async()=>{const backup=await createBackup();download(historyCSV(backup),`winter-arc-historial-${backup.exportedAt.slice(0,10)}.csv`,'text/csv;charset=utf-8');setStatus('Historial legible preparado para descargar.');})}>Descargar historial CSV</button></div><label>Revisar una copia de esta misma cuenta<input type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];setPreview(null);if(file)void action(async()=>{if(file.size>20*1024*1024)throw new Error('La copia supera el tamaño máximo de 20 MB.');const result=await previewBackup(JSON.parse(await file.text()));setPreview(result);setStatus('Copia validada. Revisa el resumen antes de recuperar.');});}}/></label>{preview&&<section><p>Copia del {new Date(preview.backup.exportedAt).toLocaleString('es-CO')} · {preview.newRecords} nuevos · {preview.identical} coincidentes · {preview.conflicts} diferencias para revisar.</p><p className="muted">Se agregarán únicamente datos que faltan. Las diferencias se conservan para revisión. Las operaciones originales recuperadas se verificarán con Supabase al sincronizar; el saldo de una copia no permite comprar hasta confirmar.</p><div className="actions"><button disabled={busy} onClick={()=>void action(async()=>{const result=await restoreBackup(preview.backup);setPreview(null);setStatus(`Recuperación terminada: ${result.newRecords} nuevos, ${result.identical} coincidentes y ${result.conflicts} diferencias. Sincroniza para verificar la copia remota.`);})}>Recuperar datos que faltan</button><button disabled={busy} onClick={()=>setPreview(null)}>Cancelar revisión</button></div></section>}</section>
 {reviews.length>0&&<section className="hero editor"><h2>Diferencias de la copia · {reviews.length}</h2><p className="muted">Tus datos actuales se conservaron. Una corrección elegida aquí queda auditada y requiere confirmación del servidor.</p>{reviews.map(review=><details key={review.id}><summary>{describe(review.value)}</summary><p>Valor actual: {currentValues[review.id]?describe(currentValues[review.id]!):'No existe un registro local compatible.'}</p><p>Valor de la copia: {describe(review.value)}</p><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),reason=String(form.get('reason')||'').trim();void action(async()=>{
 if(!reason)throw new Error('Explica el motivo de la resolución.');
 if(form.get('choice')==='backup'){
  if(review.type==='entries'){const value=review.value as Entry,current=await db.entries.get(value.id);if(!current||['day','mission','unit','note','occurredAt'].some(k=>current[k as keyof Entry]!==value[k as keyof Entry]))throw new Error('Completa la corrección desde Misiones: no existe un aporte compatible para corregir solo su cantidad.');await correctEntry(value.id,value.quantity,reason);}
  else if(review.type==='decisions'){const value=review.value as Decision;if(!await db.decisions.get(value.id))throw new Error('Registra el resultado desde Misiones para recuperar esta decisión que no tiene operación original.');let detail:Record<string,unknown>;try{detail=JSON.parse(value.detail);}catch{detail={};}await setDecision({day:value.day,mission:value.mission,result:value.result,detail:JSON.stringify({...detail,note:reason})});}
  else throw new Error('Las operaciones distintas necesitan revisión del registro o cierre desde Misiones; no se ejecutan desde la copia.');
 }
 await db.restores.update(review.id,{status:form.get('choice')==='backup'?'corrected':'kept-local',reason,resolvedAt:new Date().toISOString()});setStatus('Resolución guardada. Sincroniza las correcciones cuando tengas conexión.');
 });}}><label>Resolución<select name="choice"><option value="local">Conservar datos actuales</option>{review.type!=='operations'&&<option value="backup">Crear una corrección con el valor de la copia</option>}</select></label><label>Motivo<input name="reason" required maxLength={2000}/></label><button disabled={busy}>Guardar resolución</button></form></details>)}</section>}
 <section className="hero editor"><h2>Instalar Winter Arc</h2><p role="status">{pwa}</p><p>{online?'Con conexión':'Sin conexión'} · Los registros se guardan en este dispositivo; comprar y confirmar el saldo requieren conexión.</p>{installPrompt?<button onClick={()=>void action(async()=>{await requestInstall();})}>Instalar aplicación</button>:<p className="muted">Si tu navegador ofrece instalación, usa su menú «Instalar aplicación» o «Añadir a pantalla de inicio». En iPhone: Compartir → Añadir a pantalla de inicio.</p>}{pwaRegistration?.waiting&&<button disabled={!canUpdate||busy} onClick={()=>{navigator.serviceWorker.addEventListener('controllerchange',()=>window.location.reload(),{once:true});pwaRegistration?.waiting?.postMessage({type:'ACTIVATE_UPDATE'});}}>Aplicar actualización</button>}{!canUpdate&&<p className="muted">Guarda o cancela el formulario de registro antes de actualizar.</p>}<p className="muted">La primera apertura necesita conexión. Después, los archivos guardados y tus registros permiten trabajar sin red. La disponibilidad del botón de instalación depende del navegador.</p></section></section>;
}
